import base64
import os
import smtplib

from email.message import EmailMessage


def send_report_email(
    recipient_email,
    pdf_base64,
    filename="Textile_Prediction_Report.pdf"
):
    """
    Send a PDF report as an email attachment.
    """

    sender_email = os.getenv(
        "MAIL_USERNAME"
    )

    sender_password = os.getenv(
        "MAIL_PASSWORD"
    )

    mail_server = os.getenv(
        "MAIL_SERVER",
        "smtp.gmail.com"
    )

    mail_port = int(
        os.getenv(
            "MAIL_PORT",
            "587"
        )
    )

    mail_use_tls = os.getenv(
        "MAIL_USE_TLS",
        "true"
    ).lower() == "true"

    if not sender_email:
        raise ValueError(
            "MAIL_USERNAME is not configured."
        )

    if not sender_password:
        raise ValueError(
            "MAIL_PASSWORD is not configured."
        )

    if not recipient_email:
        raise ValueError(
            "Recipient email is required."
        )

    if not pdf_base64:
        raise ValueError(
            "PDF data is required."
        )

    # Remove data URL prefix if present
    if "," in pdf_base64:
        pdf_base64 = pdf_base64.split(
            ",",
            1
        )[1]

    pdf_bytes = base64.b64decode(
        pdf_base64
    )

    message = EmailMessage()

    message["Subject"] = (
        "Textile Waste Management AI - Report"
    )

    message["From"] = sender_email
    message["To"] = recipient_email

    message.set_content(
        """Hello,

Please find your Textile Waste Management AI report attached.

This report was generated by the Textile Waste Management AI System.

Regards,
Textile Waste Management AI System
"""
    )

    message.add_attachment(
        pdf_bytes,
        maintype="application",
        subtype="pdf",
        filename=filename
    )

    with smtplib.SMTP(
        mail_server,
        mail_port,
        timeout=30
    ) as server:

        if mail_use_tls:
            server.starttls()

        server.login(
            sender_email,
            sender_password
        )

        server.send_message(
            message
        )

    return True