import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePDF = (results) => {
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.text("AI Textile Waste Prediction Report", 14, 20);

  doc.setFontSize(11);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);

  const tableData = results.map((item) => [
    item.image,
    item.prediction,
    `${item.confidence}%`,
  ]);

  autoTable(doc, {
    startY: 40,
    head: [["Image", "Prediction", "Confidence"]],
    body: tableData,
  });

  // Summary
  const summary = {};

  results.forEach((item) => {
    summary[item.prediction] = (summary[item.prediction] || 0) + 1;
  });

  let y = doc.lastAutoTable.finalY + 15;

  doc.setFontSize(14);
  doc.text("Batch Summary", 14, y);

  y += 10;

  doc.setFontSize(11);
  doc.text(`Total Images: ${results.length}`, 14, y);

  y += 8;

  Object.entries(summary).forEach(([label, count]) => {
    doc.text(`${label}: ${count}`, 14, y);
    y += 8;
  });

  y += 10;

  doc.setFontSize(10);
  doc.text(
    "Generated by Textile Waste Management AI System",
    14,
    y
  );

  doc.save("Textile_Prediction_Report.pdf");
};